routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\PostTagController;
use App\Http\Controllers\UserCommentController;

Route::get('/', [HomeController::class, 'home'])->name('home.index');
Route::get('/about',  [HomeController::class, 'about'])->name('home.about');
Route::resource('/post', PostController::class);
Auth::routes();

Route::post('/post/{post}/comment',             [CommentController::class, 'store'])->name('comment.post.store');
Route::put('/post/{post}/comment/{comment}',    [CommentController::class, 'update'])->name('comment.post.update');
Route::delete('/post/{post}/comment/{comment}', [CommentController::class, 'destroy'])->name('comment.post.destroy');

Route::get('/post/tag/{tag}', [PostTagController::class, 'index'])->name('post.tags.index');

Route::resource('/users', UserController::class)->only(['show', 'edit', 'update']);
Route::post('/users/{user}/comment/create', [UserCommentController::class, 'store'])->name('comment.user.store')->middleware('auth');

Route::get('/mailable', function () {
    $comment = Cache::remember('mail-template', now()->addSeconds(3600), fn () => \App\Models\Comment::inRandomOrder()->first());
    return new \App\Mail\CommentPostedMarkdown($comment);
});

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Storage;
use App\Models\User;
use App\Models\BlogPost;
use Domain\Posts\ImageStorage;
use Domain\Posts\VisitCounter;
use App\Events\BlogPostCreated;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cache;
use App\Http\Requests\Post\StoreRequest as PostStore;
use App\Http\Requests\Post\UpdateRequest as PostUpdate;

class PostController extends Controller
{
    private const IMG_DIR = 'thumbnail';

    public function __construct()
    {
        $this->middleware('auth')->only(['create', 'store', 'edit', 'update', 'destroy']);
    }

    public function index()
    {
        $posts = BlogPost::with('tags')->orderBy('created_at', 'desc')->paginate(7);

        return view('posts.index', [
            'posts' => $posts,
            'most_commented' => Cache::remember('most-commented-posts', now()->addSeconds(120), fn () => BlogPost::mostCommented()->take(5)->get()),
            'most_active_users' => Cache::remember('most-active-users', now()->addSeconds(120), fn () => User::withMostBlogPostsLastMonth()->take(5)->get()),
            'active' => 'posts'
        ]);
    }

    public function create()
    {
        return view('posts.create', ['active' => 'posts']);
    }

    public function store(PostStore $request)
    {
        $post = Auth::user()->posts()->create($request->validated());

        (new ImageStorage(self::IMG_DIR))->verify($request)->store($post);
        

        event(new BlogPostCreated($post));

        $request->session()->flash('status', 'Postagem criada com sucesso!');
        return redirect()->route('post.show', ['post' => $post]);
    }

    public function show(BlogPost $post)
    {
        $post->load(['comments', 'tags', 'user', 'comments.user', 'comments.tags']);
        return view('posts.show', ['post' => $post, 'active' => 'posts', 'counter' => (new VisitCounter)->counter($post->id)]);
    }

    public function edit(BlogPost $post)
    {
        $this->authorize('posts:update', $post);

        return view('posts.edit', ['post' => $post, 'active' => 'posts']);
    }

    public function update(PostUpdate $request, BlogPost $post)
    {
        $post->update($request->validated());

        (new ImageStorage(self::IMG_DIR))->verify($request)->update($post);

        $request->session()->flash('status', 'Postagem atualizada com sucesso!');
        return redirect()->route('post.show', ['post' => $post, 'active' => 'posts']);
    }

    public function destroy(BlogPost $post)
    {
        $this->authorize('posts:destroy', $post);

        $post->delete();
        return redirect()->route('post.index', ['post' => $post, 'active' => 'posts'])->with('status', "Postagem $post->title excluida com sucesso!");
    }
}

resources/views/posts/partials/post.blade.php
<div class="card shadow-sm">
    <div class="card-body">
        <h5 class="card-title font-weight-bold @if($post->trashed()) text-muted @endif">{{$post->id}}. {{ $post->title }} @if(\Carbon\Carbon::parse($post->created_at)->between(\Carbon\Carbon::yesterday(), now()))<span class="badge badge-danger">New</span> @endif</h5>
        <x-tags :tags="$post->tags"/>
        <p class="card-text">{{ \Illuminate\Support\Str::limit($post->content, 20) }}</p>
        <div class="btn-group" style="float: left;">
            <p class="text-muted @if($post->comments->where('user_id', Auth::id())->count()) font-weight-bold @endif">{{$post->comments->count()}} @if($post->comments->count() === 1) comentário  @else comentários @endif</p>
        </div>
        <div class="btn-group" style="float: right;">
            @auth
                @can ('posts:destroy', $post) 
                    @if(!$post->trashed())
                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#excluirPostModal">Excluir</button>
                    @include('posts.modals.delete')
                    @endif
                @endcan
                @can('posts:update', $post)              
                    <a href="{{route('post.edit', $post->id)}}" class="col btn btn-secondary mx-1 rounded">Editar</a>
                @endcan
            @endauth
            <a href="{{route('post.show', $post->id)}}" class="col btn btn-primary mx-1 rounded">Acessar</a>
        </div>
    </div>
</div>