routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\PostTagController;
use App\Http\Controllers\UserCommentController;

Route::get('/', [HomeController::class, 'home'])->name('home.index');
Route::get('/about',  [HomeController::class, 'about'])->name('home.about');
Route::resource('/post', PostController::class);
Auth::routes();

Route::post('/post/{post}/comment',             [CommentController::class, 'store'])->name('comment.post.store');
Route::put('/post/{post}/comment/{comment}',    [CommentController::class, 'update'])->name('comment.post.update');
Route::delete('/post/{post}/comment/{comment}', [CommentController::class, 'destroy'])->name('comment.post.destroy');

Route::get('/post/tag/{tag}', [PostTagController::class, 'index'])->name('post.tags.index');

Route::resource('/users', UserController::class)->only(['show', 'edit', 'update']);
Route::post('/users/{user}/comment/create', [UserCommentController::class, 'store'])->name('comment.user.store')->middleware('auth');

Route::get('/mailable', function () {
    $comment = Cache::remember('mail-template', now()->addSeconds(3600), fn () => \App\Models\Comment::inRandomOrder()->first());
    return new \App\Mail\CommentPostedMarkdown($comment);
});

app/Models/Image.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Image extends Model
{
    use HasFactory;

    protected $fillable = [
        'path', 
    ];

    public function imageable()
    {
        return $this->morphTo();
    }

    public function getImageUrlAttribute() {
        return Storage::url($this->path);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Storage;
use App\Models\User;
use App\Models\BlogPost;
use Domain\Posts\ImageStorage;
use Domain\Posts\VisitCounter;
use App\Events\BlogPostCreated;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cache;
use App\Http\Requests\Post\StoreRequest as PostStore;
use App\Http\Requests\Post\UpdateRequest as PostUpdate;

class PostController extends Controller
{
    private const IMG_DIR = 'thumbnail';

    public function __construct()
    {
        $this->middleware('auth')->only(['create', 'store', 'edit', 'update', 'destroy']);
    }

    public function index()
    {
        $posts = BlogPost::with('tags')->orderBy('created_at', 'desc')->paginate(7);

        return view('posts.index', [
            'posts' => $posts,
            'most_commented' => Cache::remember('most-commented-posts', now()->addSeconds(120), fn () => BlogPost::mostCommented()->take(5)->get()),
            'most_active_users' => Cache::remember('most-active-users', now()->addSeconds(120), fn () => User::withMostBlogPostsLastMonth()->take(5)->get()),
            'active' => 'posts'
        ]);
    }

    public function create()
    {
        return view('posts.create', ['active' => 'posts']);
    }

    public function store(PostStore $request)
    {
        $post = Auth::user()->posts()->create($request->validated());

        (new ImageStorage(self::IMG_DIR))->verify($request)->store($post);
        

        event(new BlogPostCreated($post));

        $request->session()->flash('status', 'Postagem criada com sucesso!');
        return redirect()->route('post.show', ['post' => $post]);
    }

    public function show(BlogPost $post)
    {
        $post->load(['comments', 'tags', 'user', 'comments.user', 'comments.tags']);
        return view('posts.show', ['post' => $post, 'active' => 'posts', 'counter' => (new VisitCounter)->counter($post->id)]);
    }

    public function edit(BlogPost $post)
    {
        $this->authorize('posts:update', $post);

        return view('posts.edit', ['post' => $post, 'active' => 'posts']);
    }

    public function update(PostUpdate $request, BlogPost $post)
    {
        $post->update($request->validated());

        (new ImageStorage(self::IMG_DIR))->verify($request)->update($post);

        $request->session()->flash('status', 'Postagem atualizada com sucesso!');
        return redirect()->route('post.show', ['post' => $post, 'active' => 'posts']);
    }

    public function destroy(BlogPost $post)
    {
        $this->authorize('posts:destroy', $post);

        $post->delete();
        return redirect()->route('post.index', ['post' => $post, 'active' => 'posts'])->with('status', "Postagem $post->title excluida com sucesso!");
    }
}

resources/views/posts/_form.blade.php
<div class="mb-3 form-group">
    <label for="post-title" class="form-label font-weight-bold">Titulo</label>
    <input  type="text" id="post-title" name="title"  class="form-control" placeholder="Um gavião voo" value="{{old('title')}}">
</div>

<div class="mb-3 form-group">
    <label for="post-content" class="form-label font-weight-bold">Conteúdo</label>
    <textarea id="post-content" name="content" class="form-control" minlength="20" rows="3">{{old('content')}}</textarea>
</div>

<div class="mb-3 form-group">
    <label for="post-thumbnail" class="form-label font-weight-bold">Thumbnail</label>
    <input id="post-thumbnail" type="file" name="thumbnail" class="form-control-file">
</div>

resources/views/posts/create.blade.php
@extends('layouts.master')

@section('pagina', 'Postagens')

@section('content')

<div class="container">
    <div>
        <h1 class="text-muted font-weight-bold">Create a new post</h1>
    </div>
    <x-error :errors="$errors" />
    <div class="bg-white p-3 rounded shadow-sm">
        <form action="{{route('post.store')}}" method="POST" enctype="multipart/form-data">
            @csrf
            @include('posts._form')
            <div class="d-inline-flex">
                <a href="{{route('post.index')}}" type="button"
                    class="btn btn-secondary shadow-sm mr-2 text-capitalize">close</a>
                <x-button type="submit" :message="'Create'" />
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/posts/edit.blade.php
@extends('layouts.master')

@section('pagina', $post["title"])

@section('content')
<div class="container">
    <div>
        <h5 id="titulo" class="text-muted font-weight-bold">Atualizar postagem</h5>
        <h1 class="text font-weight-light text-dark">{{$post['title']}}</h1>
    </div>
    <x-error :errors="$errors" />
    <div class="bg-white p-3 rounded shadow-sm">
        <form id="novo-post" class="d-grid gap-3" action="{{route('post.update', $post->id)}}" method="POST" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            @include('posts._form')
            <div class="d-inline-flex">
                <a href="{{route('post.index')}}" type="button" class="btn btn-secondary shadow-sm mr-2 text-capitalize">close</a>
                <x-button type="submit" :message="'Save Changes'"/>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.master')

@section('pagina', 'Postagens')

@section('content')
<div class="container gap-2">
    @auth
        <div class="mb-2"><a type="button" class="btn btn-primary" href="{{route('post.create')}}">Nova postagem</a></div>
    @endauth

    <div class="row">
        <div class="@if (isset($most_commented) || isset($most_active_users) )col-10 @else col-12 @endif d-grid gap-3">
            @forelse ($posts as $post)
            @include('posts.partials.post')
            <br>
            @empty
                <div class="col">
                    <h1>Nenhum post encontrado!</h1>
                </div>
            @endforelse
        </div>
        @if (isset($most_commented) || isset($most_active_users) )
            <div class="col-2 justify-content-start">
                <div class="container">
                    @if (isset($most_commented))    
                        <div class="card shadow-sm mb-2" style="width: 18rem;">
                            <div class="card-body">
                                <h5 class="card-title"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-left-text" viewBox="0 0 16 16">
                                    <path d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H4.414A2 2 0 0 0 3 11.586l-2 2V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12.793a.5.5 0 0 0 .854.353l2.853-2.853A1 1 0 0 1 4.414 12H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                                    <path d="M3 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 6a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 6zm0 2.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z"/>
                                </svg> Mais comentados</h5>
                                <p class="card-text font-weight-bold">Postagens mais comentadas</p>
                            </div>
                            <ul class="list-group list-group-flush">
                                @foreach ($most_commented as $key => $value)
                                <li class="list-group-item">
                                    <a href="{{route('post.show', $value->id)}}" class="text-dark">
                                        {{$value->title}}
                                    </a>
                                </li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    @if (isset($most_active_users))    
                        <div class="card shadow-sm" style="width: 18rem;">
                            <div class="card-body">
                                <h5 class="card-title"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-graph-up" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M0 0h1v15h15v1H0V0zm10 3.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-1 0V4.9l-3.613 4.417a.5.5 0 0 1-.74.037L7.06 6.767l-3.656 5.027a.5.5 0 0 1-.808-.588l4-5.5a.5.5 0 0 1 .758-.06l2.609 2.61L13.445 4H10.5a.5.5 0 0 1-.5-.5z"/>
                                </svg> Usuarios mais ativos</h5>
                                <p class="card-text font-weight-bold">Os usuarios com maior atividade no ultimo mês</p>
                            </div>
                            <ul class="list-group list-group-flush">
                                @foreach ($most_active_users as $key => $value)
                                <li class="list-group-item ">
                                    {{$value->name}}
                                </li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                </div>
            </div>
        @endif
    </div>
    <div class="d-flex justify-content-center items-center">
        {{ $posts->links() }}
    </div>

</div>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.master')

@section('pagina', $post->title)

@section('content')
    <div class="container">
        <x-alert :message="session('status')"/>
        <div>
            <div class="d-flex shadow-sm bg-white p-3 mb-2 rounded p-3 m-3">
                <article class="blog-post">
                    <h1 class="blog-post-title text-weight-bold display-4">{{ $post->title }}</h1>
                    <p class="blog-post-meta text-muted">{{ $post->created_at->diffForHumans() }}, by <a href="{{route('users.show', ['user' => $post->user->id])}}" class="text-success">{{ $post->user->name }}</a></p>
                    <x-tags :tags="$post->tags"/>
                    <div class="d-flex my-4">
                        @if ($post->image)
                            <img src="{{$post->image->image_url}}" alt="{{$post->title}}" class="img-thumbnail img-fluid" width="300" height="400">
                        @endif
                        <p class="lead p-3 ml-3">{{ $post->content }}</p>
                    </div>

                    <div class="text-muted">Numero de acessos: {{$counter}}</div>
                </article>
            </div>
        </div>
        <div>
            @auth
                <div class="shadow-sm bg-white p-3 rounded m-3">
                    <form method="POST" action="{{ route('comment.post.store', $post->id) }}">
                        @include('comments.create')
                    </form>
                </div>
            @endauth
            @if ($post->comments->isNotEmpty())
                @include('comments.index')
            @else
                <div class="d-flex shadow-sm bg-white p-3 rounded m-3 ">
                    <article class="blog-post">
                        <p>Nenhum comentário encontrado!</p>
                    </article>
                </div>
            @endif
        </div>
    </div>
@endsection

<style>

</style>