routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\PostTagController;
use App\Http\Controllers\UserCommentController;

Route::get('/', [HomeController::class, 'home'])->name('home.index');
Route::get('/about',  [HomeController::class, 'about'])->name('home.about');
Route::resource('/post', PostController::class);
Auth::routes();

Route::post('/post/{post}/comment',             [CommentController::class, 'store'])->name('comment.post.store');
Route::put('/post/{post}/comment/{comment}',    [CommentController::class, 'update'])->name('comment.post.update');
Route::delete('/post/{post}/comment/{comment}', [CommentController::class, 'destroy'])->name('comment.post.destroy');

Route::get('/post/tag/{tag}', [PostTagController::class, 'index'])->name('post.tags.index');

Route::resource('/users', UserController::class)->only(['show', 'edit', 'update']);
Route::post('/users/{user}/comment/create', [UserCommentController::class, 'store'])->name('comment.user.store')->middleware('auth');

Route::get('/mailable', function () {
    $comment = Cache::remember('mail-template', now()->addSeconds(3600), fn () => \App\Models\Comment::inRandomOrder()->first());
    return new \App\Mail\CommentPostedMarkdown($comment);
});

app/Models/Image.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Image extends Model
{
    use HasFactory;

    protected $fillable = [
        'path', 
    ];

    public function imageable()
    {
        return $this->morphTo();
    }

    public function getImageUrlAttribute() {
        return Storage::url($this->path);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function scopeWithMostBlogPosts(Builder $builder) {
        return $builder->withCount('posts')->orderBy('posts_count', 'desc');
    }

    public function scopeWithMostBlogPostsLastMonth(Builder $builder) {
        return $builder->withCount(['posts' => function($query) {
            $query->whereBetween(static::CREATED_AT, [now()->subMonths(1), now()]);
        }])->has('posts', '>=', 1)
        ->orderBy('posts_count', 'desc');
    }

    public function scopeCommentedOnPost(Builder $builder, BlogPost $post) {
        return $builder->whereHas('comments', function($query) use ($post){
            return $query->where('commentable_id', $post->id)->where('commentable_type', BlogPost::class);
        });
    }
    
    public function scopeWhereIsAnAdmin(Builder $builder) {
        return $builder->where('is_admin', true);
    }

    public function posts() {
        return $this->hasMany(BlogPost::class);
    }

    public function comments() {
        return $this->hasMany(Comment::class);
    }

    public function commentsOn() {
        return $this->morphMany(Comment::class, 'commentable');
    }

    public function image() {
        return $this->morphOne(Image::class, 'imageable');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Domain\Posts\ImageStorage;
use App\Http\Controllers\Controller;
use App\Http\Requests\User\UpdateRequest as UserUpdate;

class UserController extends Controller
{
    private const IMG_DIR = 'avatar';

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function show(User $user)
    {
        $this->authorize('user:view', $user);
        $user->load('commentsOn');
        return view('users.profile.show', compact('user'));
    }

    public function edit(User $user)
    {
        $this->authorize('user:update', $user);
        return view('users.profile.edit', compact('user'));
    }

    public function update(UserUpdate $request, User $user)
    {
        (new ImageStorage(self::IMG_DIR))->verify($request)->update($user);

        return redirect()->back()->with('status', 'Profile image was updated');
    }
}

resources/views/users/profile/edit.blade.php
@extends('layouts.master')
@section('pagina', 'Profile')

@section('content')
    <div class="container">
        <x-alert :message="session('status')"/>
        <x-error :errors="$errors"/>
        <div class="bg-white rounded p-2 shadow-sm">
            <form method="POST" action="{{route('users.update', ['user' => $user->id])}}" class="form-horizontal" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="row">
                    <div class="col-4">
                        <img src="{{$user->image ? $user->image->image_url : ''}}" alt="{{$user->name}}" class="img-thumbnail avatar"/>
    
                        <div class="card mt-4">
                            <div class="card-body">
                                <h6>Upload a different foto</h6>
                                <input type="file" name="avatar" class="form-control-file">
                            </div>
                        </div>
                    </div>
                    <div class="col-8">
                        <div class="form-group">
                          <label for="name">Name:</label>
                          <input type="text" name="name" id="name" class="form-control"/>
                        </div>
                        <div class="form-group">
                            <x-button type="submit" :message="'Save Changes'" />
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/users/profile/show.blade.php
@extends('layouts.master')
@section('pagina', 'Profile')

@section('content')
<div class="container">
    <div class="bg-white p-3 m-3 rounded-sm shadow-sm">
        <div class="row">
            <div class="col-4">
                <img src="{{$user->image ? $user->image->image_url : ''}}" alt="{{$user->name}}"
                    class="img-thumbnail avatar" />
            </div>
            <div class="col-8 justify-content-center align-content-center">
                <h3 class="text-muted">{{ $user->name }}</h3>
            </div>
        </div>
    </div>
    @auth
        <div class="shadow-sm bg-white p-3 rounded m-3">
            <form method="POST" action="{{ route('comment.user.store', $user->id) }}">
                @include('comments.create')
            </form>
        </div>
    @endauth
    @if ($user->commentsOn->isNotEmpty())
        @include('comments.userIndex')
    @else
    <div class="d-flex shadow-sm bg-white p-3 rounded m-3 ">
        <article class="blog-post">
            <p>Nenhum comentário encontrado!</p>
        </article>
    </div>
    @endif
</div>
@endsection